### ISSUE TITLE
AppDomain isolation support for dnx451 CLR in xunit

### ISSUE THREAD

**Issue by cherrydev** [aspnet/Testing#106]
It seems desirable that support for isolated AppDomains be available when running on a platform that supports it.  Currently xunit's aspnet execution environment uses a single code path for both aspnetcore50 and dnx451 that excludes AppDomain isolation.
I've discussed the issue with @bradwilson [on the xunit project](https://github.com/xunit/aspnet.xunit/issues/26) and isn't convinced of the idea of using conditional compilation to support this scenario.
As far as I understand, the "desktop" runner will not operate inside of a .xproj environment because it doesn't know how to load the assemblies from these projects.
I believe it would be very simple to use different `frameworks.<frameworkName>.complationOptions.define` options to provide this.
Does anybody here have any opinion on this?
I understand that the whole new aspnet stack is designed to minimize the need to have isolation like this by having much less global state, but many of us are still stick with 3rd party libraries that cause testing to be a pain.

**Comment by Eilon** [comment]
There are no plans to implement this in the DNX test host. You might be able to implement this using xUnit's existing `FactAttribute` extensibility.
