### ISSUE TITLE
System.NullReferenceException when run dnx . test

### ISSUE THREAD

**Issue by cuiliang** [aspnet/Testing#112]
Version: xunit.runner.aspnet(2.0.0-aspnet-beta5-10345)

tests can be executed in VS2015RC successfully,
but when run in cmd, it displays:

System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 Xunit.Runner.AspNet.Program.Main(String[] args)
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 Microsoft.Framework.Runtime.Common.EntryPointExecutor.Execute(Assembly assembly, String[] args, IServiceP rovider serviceProvider)
   在 Microsoft.Framework.ApplicationHost.Program.ExecuteMain(DefaultHost host, String applicationName, String[ ] args)
   在 Microsoft.Framework.ApplicationHost.Program.Main(String[] args)
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 Microsoft.Framework.Runtime.Common.EntryPointExecutor.Execute(Assembly assembly, String[] args, IServiceP rovider serviceProvider)
   在 dnx.host.Bootstrapper.RunAsync(List`1 args)
   在 dnx.host.RuntimeBootstrapper.ExecuteAsync(String[] args)
   在 dnx.host.RuntimeBootstrapper.Execute(String[] args)

**Comment by Bartmax** [comment]
You need the latest bits for beta5

https://github.com/xunit/dnx.xunit/issues/28

**Comment by pemari-msft** [comment]
Did you ever figure this out, @cuiliang ? I have the same issue but with xunit.runner.dnx 2.1.0.

**Comment by Alxandr** [comment]
If I'm not mistaken, this is an issue that generally happen if you have incompatible versions of `dnx` and `xunit.runner.dnx`. Either upgrade the xunit runner to a nightly, or downgrade dnx.
