### ISSUE TITLE
ReplaceCulture cannot be used to specify different cultures from the default.

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Testing#126]
Today `Culture`/`UICulture` are `CultureInfo`s and therefore cannot be specified (compile error).

**Comment by dougbu** [comment]
Oops, these properties changed from the `string`s they were in MVC 5 and so on for some reason.

**Comment by Eilon** [comment]
If there are properties on this attribute that are effectively unsettable then we should remove the setters (the getters are fine).

**Comment by kichalla** [comment]
eb727006987e2dac556e1924e7610b26560562b5
