### ISSUE TITLE
DNX Core 5.0 tests are not discovered in the TestExporer

### ISSUE THREAD

**Issue by lukaskabrt** [aspnet/Testing#127]
It seems, that Test Explorer is unable to show tests if the test project doesn't use `dnx451` in the frameworks section. 

If `"dnx451": {}` is removed from the `project.json`, then all tests disappear from the Test Explorer, but they are still discovered by `dnx . test` command. According to (https://github.com/xunit/dnx.xunit/issues/39#issuecomment-116365912) the issue is within plugin that bridges Test Explorer - DNX and not within XUnit library.

**project.json**

```
{
    "version": "1.0.0-*",
    "description": "",
    "authors": [ "" ],
    "tags": [ "" ],
    "projectUrl": "",
    "licenseUrl": "",

    "dependencies": {
        "xunit": "2.1.0-beta2-build2981",
        "xunit.runner.dnx": "2.1.0-beta2-build79"
    },
    "commands": {
        "test": "xunit.runner.dnx"
    },
  "frameworks" : {
    "dnxcore50": {
        "dependencies": {
            "System.Collections": "4.0.10-beta-22816",
            "System.Linq": "4.0.0-beta-22816",
            "System.Threading": "4.0.10-beta-22816",
            "Microsoft.CSharp": "4.0.0-beta-22816"
        }
    },
    "dnx451": {}
  }
}
```

**Comment by danroth27** [comment]
@vijayrkn @rynowak  Can you guys take a look at this?

**Comment by Eilon** [comment]
This issue was moved to aspnet/Tooling#186
