### ISSUE TITLE
Figure out a way to handle application wide exceptions in cross-plat way in the xunit runner

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Testing#13]
As part of the runner, we attempt to hook on to UnhandledException event of the current AppDomain to handle exceptions globally
https://github.com/aspnet/Testing/commit/365e1071de5c4aa9603fa30af772a56b474b8ae6#diff-619d8effcebaab8df0b93807d7ee757aR41

However AppDomain was removed from CoreCLR. I've currently ifdefed the AppDomain references to Net45 only. We'll need a better way to do this.

**Comment by davidfowl** [comment]
@ellismg @jkotas ?

**Comment by davidfowl** [comment]
@pranavkm File this on the corefx/coreclr repository. This seems like something that could come back.
