### ISSUE TITLE
Add an environment variable to trace more information to VS output window

### ISSUE THREAD

**Issue by rynowak** [aspnet/Testing#137]
After discussion with @BillHiebert we want to go a similar route to how VS handles tracing from DTH.

We should add an environment variable that enables tracing in TestHost. VS should also be aware of this environment variable, and when it's set, pass the output of TestHost through to the Test output window via `IFrameworkHandle`.

**Comment by Eilon** [comment]
Moved to here: https://github.com/aspnet/Tooling-Internal/issues/465
