### ISSUE TITLE
Remove Microsoft.Dnx.Runtime dependency from TestHost

### ISSUE THREAD

**Issue by muratg** [aspnet/Testing#148]
https://github.com/aspnet/Testing/blob/dev/src/Microsoft.Dnx.TestHost/project.json#L17

I hear this is only used for parsing project.json files. TestHost should depend on Json.NET instead.

@rynowak @davidfowl

**Comment by rynowak** [comment]
What you heard is super accurate.

**Comment by kichalla** [comment]
51fe8a564c0b230023358e33a1e188da725321f8
1728b3aa4281aac968310e846ca8fe94034869cc
