### ISSUE TITLE
Rename Microsoft.Dnx.TestAdapter to Microsoft.Dnx.Testing.Abstractions

### ISSUE THREAD

**Issue by davidfowl** [aspnet/Testing#158]
So that we match our naming convention everywhere else /cc @rynowak @Eilon @muratg

**Comment by muratg** [comment]
@rynowak will you have time this week?

**Comment by Eilon** [comment]
Putting on @kichalla 's plate. Please sync with @rynowak and/or @davidfowl on this before starting.

**Comment by davidfowl** [comment]
Heads up @bradwilson

**Comment by kichalla** [comment]
2dcf411e6533fc62b91db3351ababecbac373a1a
