### ISSUE TITLE
Close Solution while tests are running results in hung test process until VS closes.

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Testing#164]
**Repro:**
1. Run all tests.
1. File => Close solution once half the tests have been run (will need a significant amount of tests so they don't run too quick).

**Result:**
(After several repetitions)
![image](https://cloud.githubusercontent.com/assets/2008729/10235639/dd64da64-6852-11e5-9bd1-f05f551b57ac.png)

**Extra:**
If you close VS, all processes go away.

**Comment by Eilon** [comment]
@kichalla can you take a look for RC?

**Comment by kichalla** [comment]
good catch @NTaylorMullen... @Eilon sure I will take a look at it...

**Comment by kichalla** [comment]
Created an issue in tooling https://github.com/aspnet/Tooling/issues/234
