### ISSUE TITLE
[ConditionalFact] [ConditionalTheory] are broken

### ISSUE THREAD

**Issue by rynowak** [aspnet/Testing#174]
As of this change: https://github.com/aspnet/Testing/commit/87ca8dff1bc071e90f68cae72d7a751838fc377e#diff-8628424002613acec4575dfa4ce6b336L10

Neither of these attributes are discovered when running tests. They are simply missing. Look at `Microsoft.Dnx.TestHost.Tests` - it reports only 9 tests when there should be far more.

**Comment by pranavkm** [comment]
We'll revert the change to remove the runner dependency and modify the runner to cross compile to `net451` and `dotnet5.4`.
