### ISSUE TITLE
Remove OperatingSystems enum in favor of PlatformAbstractions.Platform

### ISSUE THREAD

**Issue by anurse** [aspnet/Testing#191]
`Microsoft.Extensions.PlatformAbstractions` now has a `Platform` enum that could replace `Microsoft.AspNet.Testing.OperatingSystems`. We should use that (but it involves changing ALL the repos :))

**Comment by Eilon** [comment]
Is it worth changing this? Or is it just for convenience?

**Comment by anurse** [comment]
It's mostly just to remove unnecessary duplication. Unfortunately it's harder than originally thought because Platform just specifies "Windows" whereas our OperatingSystems enum specified some Windows versions as well.

**Comment by dougbu** [comment]
Suggest instead making `OperatingSystems` a `[Flags]` enum. This would make `OperatingSystems` clearly different from `Platform`: A running system only has one `Platform` while it should be possible to exclude multiple `OperatingSystems`es. Even better this would make `OperatingSystems`more like `RuntimeFrameworks`, allowing `[OSSkipCondition]` to be used in the same ways as `[FrameworkSkipCondition]` e.g. `[OSSkipCondition(OperatingSystems.Linux | OperatingSystems.MacOSX)]`.

**Comment by anurse** [comment]
Yeah, I agree there. I was surprised when I saw it wasn't a flags. Given it's purpose, it makes sense to have it as it's own enum, but we should mark it as flags. Maybe also clean it up a little bit. I noticed that there were some platforms you couldn't express with it (like certain Windows versions)

**Comment by Eilon** [comment]
@dougbu can you take a crack at this?

**Comment by dougbu** [comment]
:ok: sure

**Comment by Eilon** [comment]
Closing this. Please let me know if you feel strongly otherwise.
