### ISSUE TITLE
Remove or Update TestPlatformHelper 

### ISSUE THREAD

**Issue by JunTaoLuo** [aspnet/Testing#193]
Seems like after https://github.com/aspnet/PlatformAbstractions/pull/9 we should be using `PlatformServices.Default.Runtime.OperatinSystemPlatform` instead of `TestPlatformHelper`. If we want to keep the helper we should use `OperatingSystemPlatform` for comparison instead.

**Comment by dougbu** [comment]
I'll take the "update" option. Self-assigning.

**Comment by dougbu** [comment]
Hmm, can't give this one a milestone since RC2 doesn't exist in this repo.

**Comment by dougbu** [comment]
84cb34d
