### ISSUE TITLE
Test discovery throws SocketException randomly

### ISSUE THREAD

**Issue by richardmatsu** [aspnet/Testing#197]
For some time now, test discovery will throw SocketException randomly in different test projects. The end result of this is after every build your unit test count will vary depending on which project's discovery failed.

Using: "xunit.runner.dnx": "2.1.0-rc1-build204"
DNX version: rc1-update1

The following logs are generated in the Test Output window:

Connected to Microsoft.Dnx.TestHost
Discovering tests in 'C:\MyProject.Tests\project.json'

System.Net.Sockets.SocketException (0x80004005): Only one usage of each socket address (protocol/network address/port) is normally permitted
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at Microsoft.Dnx.TestHost.ReportingChannel.ListenOn(Int32 port)
   at Microsoft.Dnx.TestHost.Program.<>c__DisplayClass0_0.<<Main>b__0>d.MoveNext()
Timed out waiting for a response from the test host.

**Comment by mswolfe** [comment]
I am seeing the same issue.

This only occurs when I have more than one test project and it is exacerbated as the number of unit test projects increase.  I had six unit test projects and discovery almost always threw this exception.  I then combined all of my tests into a single unit test project and this exception is never thrown.

It would be great to get a solution to this!

**Comment by StanislavPrusac** [comment]
Same problem with 3 test projects in solution, same error
"xunit.runner.dnx": "2.1.0-rc1-build204"
DNX version: 1.0.0-rc1-final

**Comment by ChrisWalford** [comment]
Just like to add my +1 to this issue.

Same error, stack trace and versions as the comments above

**Comment by DigTK** [comment]
Same problem here, 3 test projects in solution and this error happens intermittently.

Connected to Microsoft.Dnx.TestHost
Discovering tests in 'C:\Project.Tests\project.json'

System.Net.Sockets.SocketException (0x80004005): Only one usage of each socket address (protocol/network address/port) is normally permitted
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at Microsoft.Dnx.TestHost.ReportingChannel.ListenOn(Int32 port)
   at Microsoft.Dnx.TestHost.Program.<>c__DisplayClass0_0.<<Main>b__0>d.MoveNext()
Timed out waiting for a response from the test host.
========== Discover test finished: 0 found (0:00:03.151) ==========



PM> dnx --version
Microsoft .NET Execution environment
Version:      1.0.0-rc1-16231
Type:         Clr
Architecture: x86
OS Name:      Windows
OS Version:   6.1
Runtime Id:   win7-x86



"xunit": "2.1.0",
"xunit.runner.dnx": "2.1.0-rc1-build204"

**Comment by timbilt** [comment]
Same issue:

> System.Net.Sockets.SocketException (0x80004005): Only one usage of each socket address (protocol/network address/port) is normally permitted
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at Microsoft.Dnx.TestHost.ReportingChannel.ListenOn(Int32 port)
   at Microsoft.Dnx.TestHost.Program.<>c__DisplayClass0_0.<<Main>b__0>d.MoveNext()

> Microsoft .NET Execution environment
 Version:      1.0.0-rc1-16609
 Type:         Clr
 Architecture: x86
 OS Name:      Windows
 OS Version:   6.1
 Runtime Id:   win7-x86

Pretty annoying as I'm running tests quite often and I have to rebuild many times to avoid this error.

**Comment by Eilon** [comment]
This issue has been fixed for the ASP.NET Core RC2 tooling (not yet available publicly).
