### ISSUE TITLE
Convert TestHost to dnx?

### ISSUE THREAD

**Issue by victorhurdugaci** [aspnet/Testing#201]
Not sure how's the future going to look like for TestHost which is dnx-based now. @rynowak  ?

**Comment by rynowak** [comment]
I'd reckon that the future looks a lot like https://github.com/dotnet/cli/tree/master/src/Microsoft.DotNet.Tools.Test

We can just delete this when the migration is complete.

**Comment by Eilon** [comment]
Closing this because ultimately we'll remove the DNX stuff from here anyway.
