### ISSUE TITLE
Environment variables are not available during unit test execution.

### ISSUE THREAD

**Issue by mswolfe** [aspnet/Testing#202]
Hi,

I'm writing xunit tests against class libraries targeting dnxcore50.  I've added environment variables to the launchSettings.json file via the Project's properties page, but when I debug the unit test the environment variables are not present.  Is this the expected way to add environment variables that are used during test execution?

Here's what my project.json looks like:
```
{
  "version": "1.0.0-*",
  "description": "",
  "authors": [ "" ],
  "tags": [ "" ],
  "projectUrl": "",
  "licenseUrl": "",

  "dependencies": {
    "xunit": "2.1.0",
    "xunit.runner.dnx": "2.1.0-rc1-build204",
    "Microsoft.CSharp": "4.0.1-beta-*",
    "System.Collections": "4.0.11-beta-*",
    "System.Linq": "4.0.1-beta-*",
    "System.Runtime": "4.0.21-beta-*",
    "System.Threading": "4.0.11-beta-*"
  },
  "commands": {
    "test": "xunit.runner.dnx"
  },
  "frameworks": {
    "dnxcore50": { }
  }
}
```

Here's the launchSettings.json
```
{
  "profiles": {
    "test": {
      "commandName": "test",
      "environmentVariables": {
        "environment": "local"
      }
    }
  }
}
```

Thanks for the help!

**Comment by zhiliangxu** [comment]
Same issue observed with the below library versions.
    "xunit": "2.1.0",
    "xunit.runner.dnx": "2.1.0-rc1-build204",
    "Microsoft.AspNet.TestHost": "1.0.0-rc1-final"

**Comment by zhiliangxu** [comment]
Same issue observed.

**Comment by Eilon** [comment]
Seems related: https://github.com/aspnet/Mvc/issues/4230

**Comment by Eilon** [comment]
I moved the bug here: https://github.com/aspnet/Tooling/issues/456

So closing this one.
