### ISSUE TITLE
xunit.runner.console is not discovering ConditionalFacts

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/Testing#203]
xunit.console.exe does not discover tests marked with `ConditionalFact` or `ConditionalTheory`. KoreBuild is using this to run testing for full .NET

**Comment by rynowak** [comment]
This is likely because two versions of xUnit are getting loaded into the process because of `Microsoft.AspNet.Testing`'s dependencies.

**Comment by natemcmaster** [comment]
It looks like it is the same issue as discovered in https://github.com/xunit/xunit/issues/669. When executing with -noappdomain the tests appear to be discovered

**Comment by natemcmaster** [comment]
NB upgrading to xunit 2.2 beta 1 isn't an option for work around as this apparently has even more issues with test discovery. https://github.com/xunit/xunit/issues/760

**Comment by natemcmaster** [comment]
To fix this, other tests projects need to switch from  "dnx451" to "net451". 

There are no more changes to fix here. Merged in 254a19acc7ddcc4a8b229b8e4fd9cebd98f8096b
