### ISSUE TITLE
Run all tests in solution

### ISSUE THREAD

**Issue by NickAb** [aspnet/Testing#207]
I am using `xunit.runner.dnx` for `test` command and able to run tests for each project separately form command line. But I would like to be able to run all tests in solution at once.
Does the runner support such functionality?

Also, what will be the best way to run tests on CI (assuming I will only build for dnx451)?

**Comment by Eilon** [comment]
@NickAb we're making some big changes here as part of the update to dotnet-cli (https://github.com/dotnet/cli/) so there should be improved functionality in the next preview release.

**Comment by NickAb** [comment]
Great! Looking forward.

**Comment by Eilon** [comment]
The DNX-based runner has been replaced with the new [.NET CLI](https://github.com/dotnet/cli) runner. Can you try that out and see if it has the features you need? If anything is missing, please log an issue at https://github.com/dotnet/cli/issues/.

I know that for building ASP.NET/EF we have a script that looks for all the `project.json` files in the `test/` folder and compiles/runs the tests in each one individually (with some amount of parallelism). You can see our script here: https://github.com/aspnet/KoreBuild/blob/dev/build/shade/_k-standard-goals.shade#L208-L249

**Comment by NickAb** [comment]
Thanks, I will checkout .NET CLIE once we start migrating to rc2.
Meanwhile I made a PowerShell script similar to what is in .shade file.

**Comment by Eilon** [comment]
Great!
