### ISSUE TITLE
Breakpoints being skipped and code flow erratic testing with xUnit DNX

### ISSUE THREAD

**Issue by drobertson123** [aspnet/Testing#216]
I have been trying to debug my source code by triggering xUnit tests. I am placing breakpoints in my source and running the tests under Tests/Debug/All Tests. One or two of the breakpoints may get hit, but many are getting skipped. When I do hit a breakpoint and try to step through the code it seems to step almost randomly through my code, hitting places that are not sequential and often jumping to unrelated sections of code.

I pretty much can't use this to debug at all. 

I even tried adding
`System.Diagnostics.Debugger.Launch();`
before the breakpoints and it seems to do nothing.

This is a data layer class library working with Azure Data Stores. In this section of the code I am just hitting a Static Method for parsing a date. Nothing terribly complicated as far as the code goes. This is the only test that is set up. It has 4 sets of inline data for the Assert.Equal tests.

Not sure if any of that is important, but figured I would be thorough.

I am targeting
DNX 4.5.1
DNX SDK 1.0.0-rc1-update1
Using xUnit
    "xunit": "2.1.0",
    "xunit.runner.dnx": "2.1.0-rc1-build204"
  "commands": {
    "test": "xunit.runner.dnx"
  }

**Comment by drobertson123** [comment]
Update, after more investigation I believe I determined the overall problem. The ASP.NET and .NET core projects I was debugging seem to default to some form of JITTracking disabled and JITOptimizer enabled, . This is true even when you run the program in Debug mode.
After ripping my hair out for nearly a day I was not able to figure out where to set these values in VS 2015 and at this point I believe there are no obvious settings for these values and the default settings do not allow proper debugging even when you run under debug.

The workaround I used was to have an AssemblyInfo.cs file (in my Class Library project) and add the following line;

[assembly: DebuggableAttribute(true, true)]

This modifies the assembly so that the following settings are true;

isJITTrackingEnabled = True
isJITOptimizerDisabled = True

With this change I was able to effectively debug the classes.

This still leaves the problem that you lose a lot of execution efficiency by leaving these settings in place. If there is a way to set these values in the debug and release build profiles I would like to know how, otherwise I need to manual change the code before each release.

**Comment by moozzyk** [comment]
@drobertson123 - I don't know what the issue might with the debugging might be (@BillHiebert might know) but for your workaround you can #ifdef the attribute and have it only in debug builds.

**Comment by Eilon** [comment]
As far as we know this is fixed when using .NET CLI and the ASP.NET Core RC2 tooling. With .NET CLI all the DLLs and PDBs are written to disk (with DNX they were often in memory). As such we expect fewer issues, if any, related to finding these objects.

**Comment by msollicito** [comment]
I am experiencing this problem with .net core 1.1 - if I try to run tests using Xunit sometimes the debugger stops at breakpoints and sometimes does not - I will try your solution
