### ISSUE TITLE
Move the project tool scenario tester here

### ISSUE THREAD

**Issue by victorhurdugaci** [aspnet/Testing#217]
Move it from dotnet-watch so we can use it to test other tools (UserSecrets, IIS publish, etc).

**Comment by Eilon** [comment]
What exactly is this? Where is it located now?

**Comment by victorhurdugaci** [comment]
The scenario tester is a set of helpers for testing commands in project.json. It's currently located in dotnet-watch:  https://github.com/aspnet/dotnet-watch/blob/dev/test/Microsoft.DotNet.Watcher.Tools.FunctionalTests/Scenario/ProjectToolScenario.cs

**Comment by Eilon** [comment]
Ah, ok. Enjoy 😄
