### ISSUE TITLE
Improving the unit testing framework

### ISSUE THREAD

**Issue by OnamChilwan** [aspnet/Testing#220]
I was wondering whether in `MVC 6` (or even later) you could unit test a controller but not via the classic approach of instantiating the controller but instead exercise it via a mock browser? What I mean is, like how `Nancy` does this which allows me to also exercise the routes.

For example, I have a fairly basic controller in play which has a single operation and the model I am using is also shown below:

    [Route("api")]
    public class ProductsController : Controller
    {
        [HttpGet("products")]
        public async Task<IActionResult> Get()
        {
            var products = new List<Product>
                           {
                               new Product { Code = "", Description = "", Quantity = 1 },
                               new Product { Code = "", Description = "", Quantity = 1 },
                               new Product { Code = "", Description = "", Quantity = 1 }
                           };

            return this.Ok(products);
        }
    }

    public class Product
    {
        public string Code { get; set; }

        public string Description { get; set; }

        public int Quantity { get; set; }
    }

Currently, I have to do this:

    public class ProductControllerTests
    {
        [Fact]
        public async Task When_Requesting_Products()
        {
            var subject = new ProductsController();
            var result = await subject.Get() as HttpOkObjectResult;

            Assert.Equal(result.StatusCode, (int)HttpStatusCode.OK);
        }
    }

Although this is an overly simplistic test you get what I am trying to do. I was wondering, now that this is being redone from scratch wouldn't it be the ideal time to be able to mock the browser so we can exercise the entire stack but without actually going over HTTP? In Nancy this can be done via the Browser object so I don't instantiate the controller directly. 

Are there any plans to do this?

**Comment by rynowak** [comment]
As part of building MVC, we write tests at the HTTP layer - you can find some examples here: https://github.com/aspnet/Mvc/blob/dev/test/Microsoft.AspNetCore.Mvc.FunctionalTests/AntiforgeryTests.cs#L24 (anything in the functional tests project). This seems to be at a similar level of abstraction to the examples that I found looking at https://github.com/NancyFx/Nancy/wiki/Testing-your-application.

What you're running in this mode - using [TestServer](https://github.com/aspnet/Hosting/tree/dev/src/Microsoft.AspNetCore.TestHost) - your tests include running the HTTP stack as well as routing and model binding. 

Let us know more about what you're looking for if this isn't a good fit.

The dricer

**Comment by OnamChilwan** [comment]
Apologies for the response delay just got time to look into it. Looking at those tests they don't seem to at unit level but exercising the whole stack, as in going via HTTP.

https://github.com/aspnet/Mvc/blob/fbd7110da0223f6b60ab264e2bba0847d383de12/test/WebSites/BasicWebSite/Startup.cs

The test you pointed me towards utilizes the above class (correct me if I am wrong). I was thinking of the framework being able to exercise route constraints but not going via HTTP? A nancy unit test would look like.

The really cool feature I like about Nancy is how we use the `Browser `object to test the operation as opposed to what I had before, creating an instance of the controller itself.

I apologies for the formatting in advance :)

```
        [Test]
        public void Successfully_Retrieving_A_Customer()
        {
			Browser browser;
			BrowserResponse response;
			Mock<IGetCustomerQuery> getCustomerQuery;
		
            getCustomerQuery = new Mock<IGetCustomerQuery>();
            browser = new Browser(
                with =>
                {
                    with.AllDiscoveredModules();
                    with.ResponseProcessor<JsonProcessor>();
                    with.Dependencies(getCustomerQuery.Object);
                });		
		
            const int CustomerId = 123;
            var customer = new Customer
            {
                Forename = "Onam",
                Surname = "Chilwan",
                DateOfBirth = new BirthDate
                {
                    Day = 23,
                    Month = 8,
                    Year = 1984
                }
            };
            
			getCustomerQuery.Setup(x => x.Execute(customerId)).Returns(customer);
            response = browser.Get($"api/customers/{customerId}",
                with =>
                {
                    with.HttpRequest();
                });
			
			Assert.That(response.StatusCode, Is.EqualTo(HttpStatusCode.OK));
            var customer = this.response.Body.DeserializeJson<Customer>();
            Assert.That(customer.Forename, Is.EqualTo("Onam"));
            Assert.That(customer.Surname, Is.EqualTo("Chilwan"));
            Assert.That(customer.DateOfBirth.Day, Is.EqualTo(23));
            Assert.That(customer.DateOfBirth.Month, Is.EqualTo(8));
            Assert.That(customer.DateOfBirth.Year, Is.EqualTo(1984));
        }
```
