### ISSUE TITLE
Remove unnecessary imports

### ISSUE THREAD

**Issue by javiercn** [aspnet/Testing#224]
Issue to track removing unnecessary imports from this repository. Currently waiting on Xunit support for net standard. See https://github.com/xunit/xunit/issues/872

**Comment by Eilon** [comment]
@javiercn @ajaybhargavb @pranavkm we can close this right?

**Comment by Eilon** [comment]
Ping?

**Comment by pranavkm** [comment]
Yup. The project no longer has any imports.

**Comment by Eilon** [comment]
Thanks!
