### ISSUE TITLE
Please Update Wiki

### ISSUE THREAD

**Issue by PivotalAnimal** [aspnet/Testing#229]
I am trying to copy test code from Microsoft.AspNetCore.Identity.Test but the Wiki is out of date and not too useful. Thanks!

**Comment by Eilon** [comment]
Indeed, the info is quite ancient! We'll get it updated.

**Comment by Eilon** [comment]
Finally got around to this. I changed the wiki page to just point to https://docs.asp.net/en/latest/testing/index.html.
