### ISSUE TITLE
Test project doesn't reference main development project

### ISSUE THREAD

**Issue by RonCass** [aspnet/Testing#231]
I have tried numerous times now to add a test project to a few AspNetCore Projects I have and they all have the same issue, that you can not reference the main project from the test project.

You can right click references on the test project, and check the boxes next to the other projects in your solution which works fine. But after that, when you create a test class with a test method and you try to arrange the test controller like:
HomeController controller = new HomeController();

You will not be able to create the reference. If you try to put a using statement in to the main project, it will not resolve to that project.

To recreate:
Step1: Create a new solution, choose ASP.Net Core Web Application (.NET Core)., choose the .Net Framework 4.6.1. (Project 1)
Step2: Add another project to the solution, choose a (Unit Test Project Visual C# Project) with the same framework version of 4.6.1. (Test Project)
Step3: In the Test Project, try to create a test for the home controller in project with a reference to that HomeController in project 1.
Results:
 No combination of adding references or using statements should work.

**Comment by Eilon** [comment]
@RonCass it seems like the issue you have is that a CSPROJ file in VS cannot directly reference an XPROJ (project.json) project. This is a feature that will be added in an update to the .NET Core tooling for Visual Studio.

What you can do instead in the meantime is this:

1. Create your ASP.NET Core web application (running on .NET Core or .NET Framework, doesn't matter which)
2. Create a .NET Core **Class Library** project, but then change its project.json to use the same `frameworks` items as your web app project.
3. Then you can add a reference from the class library to the web app
4. Then in the class library write your unit tests

I believe that at this time perhaps only xUnit.net tests are supported.

Improvements are coming to all these areas in updated tooling, so unfortunately right now there are some manual steps.

**Comment by RonCass** [comment]
@Eilon Thanks Eilon, at least now I know why it's happening and have a workaround so I can still create unit tests. :)

**Comment by Eilon** [comment]
Closing because this will no longer be a problem in the unified CSPROJ/MSBuild world.
