### ISSUE TITLE
Create "xunit" logger provider

### ISSUE THREAD

**Issue by anurse** [aspnet/Testing#243]
In xunit, it is recommended that "console" output be written to `ITestOutputHelper` rather than the Console. We should provide a Logger to plug in to `ILoggerFactory` which writes to this. See https://github.com/aspnet/MusicStore/blob/dev/test/E2ETests/Common/XunitLogger.cs for an example.

/cc @natemcmaster

**Comment by Eilon** [comment]
We can certainly do this, but what would actually wire it up in our tests? And... what problem in our tests does it solve?

**Comment by anurse** [comment]
1. The new test host in `dotnet test` suppresses Console output. So if we want to write something out, we need to use this.

2. The `ITestOutputHelper` collects output for a single test and ensures it is rendered as a discrete unit, which is important when doing parallel testing

3. Tests would have to wire it up themselves. This is for tests that currently create a Logger Factory and attach the Console logger. Mostly functional tests that do deployment.

**Comment by Eilon** [comment]
Ah, got it, this makes sense. Are there any tests where we know we'd want to use this ASAP? I want to make sure that whoever I assign this to will have an actual use case for it 😄

**Comment by anurse** [comment]
Well there are places we already have it, https://github.com/aspnet/SignalR/blob/dev/test/Microsoft.AspNetCore.SignalR.Tests/XUnitLoggerProvider.cs , https://github.com/aspnet/MusicStore/blob/dev/test/E2ETests/Common/XunitLogger.cs , etc.

So this more about making it a common component, to avoid copy 🍝

**Comment by anurse** [comment]
Closing in lieu of aspnet/Logging#574
