### ISSUE TITLE
Regression: ConditionalTheory not always recognized

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/Testing#244]
MusicStore nano tests stopped running after this change.

Compare these test runs from Dec 22, when #239 was merged.

6 tests found and run: http://aspnetci/viewLog.html?buildId=160118&buildTypeId=XPlat_Windows_WinNanoServer_MusicStore
No tests: http://aspnetci/viewLog.html?buildId=160126&buildTypeId=XPlat_Windows_WinNanoServer_MusicStore

cc @NTaylorMullen

**Comment by NTaylorMullen** [comment]
Hmm, I made changes to fix this a while back. It was tied to how our custom test cases would serialize/deserialize. I'm curious if vstest requirements broke this (used to work).

**Comment by natemcmaster** [comment]
This is dotnet-test-xunit, not VSTest. And its broken in both.

**Comment by cesarbs** [comment]
Not fully fixed yet, need to get #252 in too.
