### ISSUE TITLE
.NET 4.5.1 test runs fail with "EXEC : warning : No test is available"

### ISSUE THREAD

**Issue by dougbu** [aspnet/Testing#248]
Since xUnit published RC1 bits, many .NET 4.5.1 test runs have started to fail with the above error. Such runs do not execute any tests. This reduces our test coverage across the repos. For example, MVC has dropped from running 6968 tests to just 3638,

Moving our xUnit dependencies back to 2.2.0-beta5-build3474 seems to work in the Performance repo. But, that's not the right fix. Should instead adjust EntityFramework, Performance , and Testing to whatever has changed in xUnit. Start with Testing because other repos use its xUnit extensions.

**Comment by dougbu** [comment]
Self-assigning

**Comment by dougbu** [comment]
Not 💯% sure but it appears xUnit has dropped .NET 4.5.1 support. Filed xunit/xunit#1102 in hopes this was unintended.

**Comment by onovotny** [comment]
.NET 4.5.1 is obsolete and unsupported by Microsoft. .NET 4.5.2 is the minimum version with support. Your unit tests need to be for .NET 4.5.2 but they can still reference .NET 4.5 libraries (as per normal referencing rules).

**Comment by dougbu** [comment]
Time to update all test projects to executing using .NET 4.5.2 instead of 4.5.1. Because it's not clear whether anything else will need to change, follow the checklist below:
- [ ] BuildTools
- [ ] Microsoft.Data.Sqlite
- [ ] PlatformAbstractions
- [ ] Common
- [ ] Testing
- [ ] JsonPatch
- [ ] FileSystem
- [ ] DependencyInjection
- [ ] Configuration
- [ ] EventNotification
- [ ] Options
- [ ] Logging
- [ ] DotNetTools
- [ ] HtmlAbstractions
- [ ] HttpAbstractions
- [ ] Caching
- [ ] Razor
- [ ] Hosting
- [ ] DataProtection
- [ ] EntityFramework
- [ ] HttpSysServer
- [ ] KestrelHttpServer
- [ ] BrowserLink
- [ ] EntityFramework.Tools
- [ ] Antiforgery
- [ ] BasicMiddleware
- [ ] Scaffolding
- [ ] IISIntegration
- [ ] AzureIntegration
- [ ] ServerTests
- [ ] ResponseCaching
- [ ] Session
- [ ] CORS
- [ ] Routing
- [ ] StaticFiles
- [ ] Proxy
- [ ] Diagnostics
- [ ] Security
- [ ] Localization
- [ ] WebSockets
- [ ] Mvc
- [ ] MetaPackages
- [ ] MvcPrecompilation
- [ ] Identity
- [ ] SignalR
- [ ] Entropy
- [ ] MusicStore
- [ ] RazorTooling (if this is still in use)
- [ ] Setup (if this is still in use)
- [ ] benchmarks
- [ ] Performance

**Comment by natemcmaster** [comment]
I've been meaning to make the following change anyways...as long as you are updating all test projects, can we make this change too?

Any project that targets:
```xml
<TargetFrameworks>netcoreapp1.1;net4XY</TargetFrameworks>
```
should change to
```xml
<TargetFrameworks>netcoreapp1.1;net4XY</TargetFrameworks>
<TargetFrameworks Condition="'$(OS)'  != 'Windows_NT'">netcoreapp1.1</TargetFrameworks>
```

This will mean only .NET Core compiles and tests on Linux.  cref https://github.com/aspnet/KoreBuild/pull/160
