### ISSUE TITLE
Allow ConditionalTheory to have an empty data collection

### ISSUE THREAD

**Issue by cesarbs** [aspnet/Testing#254]
Some Kestrel theories generate test data based on available network interfaces:

https://github.com/aspnet/KestrelHttpServer/blob/bfe1f06938eeb68f62898963c69a6e7d4a87a20a/test/Microsoft.AspNetCore.Server.Kestrel.FunctionalTests/AddressRegistrationTests.cs

Sometimes those end up with empty collections because there are no interfaces matching the required characteristics for the tests.

A way to work around that would be to have a `AllowEmptyData` parameter for `ConditionalTheory`. This would avoid having us write skip condition attributes based on specific criteria for each of those tests.

cc @halter73 @natemcmaster @Tratcher

**Comment by Tratcher** [comment]
SkipIfNoData?

**Comment by Eilon** [comment]
Adding a `SkipIfNoData` param sounds good to me.

**Comment by cesarbs** [comment]
This is messier than I thought it would be. The problem is xunit really doesn't like empty data:

https://github.com/xunit/xunit/blob/1b69df1378cb9d6b589d55ce23ab544458169485/src/xunit.execution/Sdk/Frameworks/TheoryDiscoverer.cs#L242

We'd either have to write our own discoverer that's basically a copy of xunit's without that check, or do something ugly like:

```csharp
if (results.First() is ExecutionErrorTestCase &&
    (results.First() as ExecutionErrorTestCase).ErrorMessage.StartsWith("No data found for"))
{
    ...
}
```

Given we worked around our issue in Kestrel by introducing a new attribute that checks data will be available for the test, I'm thinking of close this issue.

Unless someone really really wants this 😄

**Comment by natemcmaster** [comment]
+1 close. Sounds messy and error-prone.

**Comment by Eilon** [comment]
Fine with me, `wontfix`.
