### ISSUE TITLE
Older package from template than NuGet shows

### ISSUE THREAD

**Issue by GuardRex** [aspnet/Testing#258]
@natemcmaster I'm almost certainly opening this in the wrong spot, so please do direct me to the correct repo.

`dotnet new mstest` produces a `.csproj` with package versions for `MSTest.TestAdapter` and `MSTest.TestFramework` at `1.1.11` (with the dotnet tooling that installed with VS 2017 RTM; v1.0.0); however, [Nuget is currently showing `1.1.13`](https://www.nuget.org/packages/MSTest.TestAdapter/).

Is this an issue? We plan to put `1.1.11` in the docs because that reflects what the template provides when using `dotnet new mstest`.

**Comment by natemcmaster** [comment]
@GuardRex can you open this on https://github.com/dotnet/templating instead?
