### ISSUE TITLE
Inverse OSSkipCondition

### ISSUE THREAD

**Issue by moozzyk** [aspnet/Testing#267]
I would like to run some tests only on Win7 and Win2008R2. OSSkipCondition is only skipping specific OS/versions and doing the opposite will be hard because it would require specifying all OSes and all non-Win7/2008R2 Windows versions and it is hard to get a full list of versions.

**Comment by Eilon** [comment]
Seems like it would be easy enough to write such an attribute. Want to take a stab at it?

**Comment by moozzyk** [comment]
sure

**Comment by Eilon** [comment]
Moving to 2.1.0.

**Comment by aspnet-hello** [comment]
This issue was moved to aspnet/Home#2358
