### ISSUE TITLE
Flaky test: ConditionalFactTest.ConditionalFactSkip on Win7

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Testing#268]
```
This test should always be skipped.
Expected: True
Actual:   False
   at Microsoft.AspNetCore.Testing.ConditionalFactTest.ConditionalFactSkip() in C:\BuildAgent\work\2b0c8ce712895332\.r\Testing\test\Microsoft.AspNetCore.Testing.Tests\ConditionalFactTest.cs:line 29
```

**Comment by pranavkm** [comment]
A bit concerning since this is infrastructural code that should never fail.

**Comment by Eilon** [comment]
@javiercn - can you take a look? I want to make sure there isn't something more seriously wrong with our helper attributes.

**Comment by javiercn** [comment]
I've checked this. I haven't seen this fail on the CI lately and I've inspected the code for issues and haven't found anything that raises my concerns. I'm closing this bug, feel free to reopen if this starts happening again. @pranavkm
