### ISSUE TITLE
TimeoutAfter won't time out if the task performs a synchronous wait

### ISSUE THREAD

**Issue by anurse** [aspnet/Testing#270]
If any code in the Task being waited for does a synchronous wait, TimeoutAfter will never fire the timeout, because it is unable to schedule the timeout back over to the Xunit Sync Context.

I have a fix, just tracking this here.

**Comment by Eilon** [comment]
Go for it.

**Comment by anurse** [comment]
I was wrong about this. It doesn't seem to be something we can reliably solve without jumping off the sync context **in** the test (rather than in a helper)
