### ISSUE TITLE
Create infrastructure for testing with docker

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/Testing#277]
Requirements:

 - I should be able to write a functional test that runs .NET Core inside a Docker container
 - I should not have to manually manage the image tag or versions to ensure .NET Core runtime inside the container aligns with current KoreBuild versions
 - I should be able to assert the output of code executed from within a container, either via logs or exit code
 - I should be able to docker options, such as exposed ports, data volumes, etc.

Example: I need a way to verify the behavior added in aspnet/DataProtection#244

**Comment by natemcmaster** [comment]
cc @muratg @pakrym - this will be useful as we begin adding more docker-specific runtime features. We don't have a good way to test these at the moment.

**Comment by aspnet-hello** [comment]
This issue was moved to aspnet/Home#2356
