### ISSUE TITLE
Rewrite HttpClientSlimTests in a way that doesn't depend on Hosting

### ISSUE THREAD

**Issue by cesarbs** [aspnet/Testing#282]
Removed in 28fee6aa11ffe1238608177b7d104f99e563d30b because it broke the CI:

http://aspnetci/viewLog.html?buildId=249845&buildTypeId=UniverseCoherence&tab=buildLog#_focus=975

**Comment by Eilon** [comment]
@javiercn can you take a look?

**Comment by javiercn** [comment]
@cesarbs can you describe what the issue here is and what the expectations/goals are?

**Comment by javiercn** [comment]
How it broke the CI and what does in your opinion need to change

**Comment by cesarbs** [comment]
I thought CI links would live forever 😢 

Those tests broke the CI when moved here because they created a cycle in the dependency graph (Testing -> Hosting -> Testing IIRC).

I created this issue so this wouldn't get lost, but I'm not sure it's worth putting much effort into this. HttpClientSlim is transitively tested wherever it's used. BTW that's only Kestrel now, but it was used in MetaPackages for a while (in functional tests that used HTTPS).

**Comment by javiercn** [comment]
So can this be closed then?

**Comment by cesarbs** [comment]
It hadn't occurred to me before to use HttpListener as the server for those tests. You can look into that, but you can assign the bug to me as well since I was the one who moved HttpClientSlim here and subsequently removed its tests.

**Comment by javiercn** [comment]
@cesarbs Ok. I will do so.
