### ISSUE TITLE
NUnit test runner for KRuntime

### ISSUE THREAD

**Issue by uhaciogullari** [aspnet/Testing#34]
Will there be a test runner for NUnit? 

There is no fork of NUnit in ASP.NET repositories. How should I start if I wanted to write one myself?

**Comment by uhaciogullari** [comment]
Any progress on this? Do we have to ditch NUnit for vNext?

**Comment by plioi** [comment]
@bricelam I'm late to the party, but I've made a .NET testing framework similar to NUnit and xUnit, and the need to take out AppDomains leaves me a little confused. Without them, how is isolation achieved?  How is affecting assembly loading achieved (like setting ApplicationBase on an AppDomain)?  Many thanks for any insight you can give.

**Comment by bricelam** [comment]
@plioi the idea is that the user (or VS) invokes a command that starts a process in the context of the user's project but calling into your testing framework's entry point. App base for the process is their project, dnx resolves assemblies using their project's dependencies/references. When testing is finished, the process ends providing isolation.

**Comment by plioi** [comment]
@bricelam Ah, thanks a million!
