### ISSUE TITLE
aspnet.xunit: please fix casing of System.Xml dependency

### ISSUE THREAD

**Issue by borgdylan** [aspnet/Testing#60]
In https://github.com/aspnet/aspnet.xunit/blob/master/src/xunit.runner.kre/project.json#L9, it should be ```System.Xml``` and not ```System.XML```. As things currently are all people on Linux/Mac cannot move from ```Xunit.KRunner``` to ```xunit.runner.kre```

**Comment by juzzbott** [comment]
So, what is the solution to get this working??

**Comment by ajuckel** [comment]
FWIW, I was getting:

    System.InvalidOperationException: Failed to resolve the following dependencies for target framework 'Asp.Net,Version=v5.0':
       framework/System.XML 

And editing ~/.k/packages/xunit.runner.utility/2.0.0-rc3-build2880/xunit.runner.utility.nuspec to replace
```xml
      <frameworkAssembly assemblyName="System.XML" targetFramework="ASP.Net5.0" />
```
with
```xml
      <frameworkAssembly assemblyName="System.Xml" targetFramework="ASP.Net5.0" />
```
(changing System.XML to System.Xml) fixed it for me.  This is on a case-insensitive HFS+ macosx system, using mono 3.12 and KRE version 1.0.0-beta3-11030 of the mono runtime.

**Comment by juzzbott** [comment]
@ajuckel This fix worked for me also on Linux Mint 17. Thanks very much :)

I suppose that nuspec file could be updated in the source so that when new versions are provided, this change wont be required anymore.

**Comment by bgeihsgt** [comment]
FYI, I've submitted a pull request to xunit to fix this for good.

https://github.com/xunit/xunit/pull/336

**Comment by Yantrio** [comment]
Looks like that PR has been merged :) thanks @bgeihsgt
