### ISSUE TITLE
`[ReplaceCulture]` uses incorrect default UI culture

### ISSUE THREAD

**Issue by dougbu** [aspnet/Testing#61]
Initialization of the `ReplaceCultureAttribute.UICulture` property does not match its documentation (specifically "Defaults to en-US") or the MVC 5 code it was copied from.  The property defaults to the en-GB culture, not en-US.  This breaks compatibility with the same class in MVC 5 and may lead to inconsistent unit test results, especially as we port MVC 5 unit tests over.

Only need to change one line in the `ReplaceCultureAttribute` to fix this bug.

**Comment by Eilon** [comment]
Please fix the ctor in the attribute to set the right UICulture.

**Comment by kichalla** [comment]
eb727006987e2dac556e1924e7610b26560562b5
