### ISSUE TITLE
test runnner doesn't quit properly on a a mac

### ISSUE THREAD

**Issue by pkosel** [aspnet/Testing#62]
If I hit ctrl+c there is a message to press ctrl+c again to terminate. But it doesn't terminate. I have to kill the process manually.

**Comment by Praburaj** [comment]
This looks very similar to https://github.com/aspnet/KRuntime/issues/1017. @suhasj is there any update on this?

**Comment by suhasj** [comment]
@philippkosel You have replied to the bug https://github.com/xunit/aspnet.xunit/issues/6 on the xunit repo as well. We are currently looking into this

**Comment by Eilon** [comment]
Based on the investigation by the xunit team in https://github.com/xunit/dnx.xunit/issues/6 this appears to be a bug in Mono.
