### ISSUE TITLE
Rename Microsoft.AspNet.Logging.Testing to Microsoft.Framework.Logging.Testing

### ISSUE THREAD

**Issue by davidfowl** [aspnet/Testing#72]
I'm not sure why we called this AspNet in the first place.

/cc @muratg @glennc

**Comment by BrennanConroy** [comment]
I think it was because Microsoft.AspNet.Testing is the main part and Logging is an extension of the Testing repo, hence Microsoft.AspNet.Testing.Logging.

**Comment by muratg** [comment]
Looks like this was done. Thanks!
