### ISSUE TITLE
Tests with Conditional fact or theory does not seem to be detected by latest xunit runner

### ISSUE THREAD

**Issue by Praburaj** [aspnet/Testing#75]
I see tests in some repos not getting detected when then have conditional theory or conditionalfact attributes. See `MusicStore` or `WebListener` repos building on CI.

**Comment by Praburaj** [comment]
@victorhurdugaci @bricelam @NTaylorMullen Currently a lot of tests are not getting executed on CI. We should get this fixed sooner.

**Comment by dougbu** [comment]
@Praburaj if you use the `dougbu/attempt.testhost.fixes` branch in your aspnet/Testing repo and `build install` there, do the conditional tests start working correctly?  I was looking at a slightly different issue but may have accidentally solved this one.

**Comment by Praburaj** [comment]
@dougbu Let me check.

**Comment by Praburaj** [comment]
@dougbu that seems to fix the issue.

**Comment by Praburaj** [comment]
@dougbu could you merge the changes?

**Comment by NTaylorMullen** [comment]
Awesome, @dougbu should treat this as a build fix and get it in as soon as you can.

**Comment by dougbu** [comment]
fixed in commit d479387; forgot to update the commit description
