### ISSUE TITLE
Add package description for packages

### ISSUE THREAD

**Issue by Praburaj** [aspnet/Testing#77]
```
Testing\src\Microsoft.AspNet.Testing
Testing\src\Microsoft.Framework.Logging.Testing
Testing\src\Microsoft.Framework.TestAdapter
Testing\src\Microsoft.Framework.TestHost
Testing\src\Microsoft.Framework.TestHost\bin\Debug\app
Testing\src\StyleCop.KRules
```

**Comment by Eilon** [comment]
TestHost and TestAdapter need descriptions for sure.

**Comment by Eilon** [comment]
Proposed descriptions:

* **Microsoft.AspNet.Testing**: TBD
* **Microsoft.Dnx.TestHost**: TBD
* **Microsoft.Dnx.Testing.Abstractions**: TBD
* **Microsoft.Framework.Logging.Testing**: Helpers for writing tests that use Microsoft.Framework.Logging.
* **Microsoft.Framework.WebEncoders.Testing**: Helpers for writing tests that useMicrosoft.Framework.WebEncoders.
