### ISSUE TITLE
Improve Symbol Resolution in TestHost

### ISSUE THREAD

**Issue by davidfowl** [aspnet/Testing#86]
Found this being used in roslyn http://www.nuget.org/packages/Microsoft.DiaSymReader/1.0.4-rc2

/cc @rynowak

**Comment by rynowak** [comment]
Will take a look. Looks like it's just the COM definitions for https://msdn.microsoft.com/en-us/library/ms233503(v=vs.110).aspx

**Comment by Eilon** [comment]
The real problem here is supporting symbol line info for test cases that use async, iterators, or inherited tests.

We hope that using DiaSymReader or MetadataReader will solve this problem but we're not sure.

**Comment by rynowak** [comment]
We ended up not needing MetadataReader to do this. All the info we need is available trivially using reflection.

**Comment by rynowak** [comment]
19416813beebf9248ed49919660106e89284530f 8dd3a13e072b2b4e6a21683d597f17def02e059f

**Comment by gulbanana** [comment]
this problem is still happening for me in 1.0/rtm when there is an async test in a base class.

**Comment by rynowak** [comment]
@gulbanana - please open a new issue on https://github.com/dotnet/cli - they own this functionality now.

**Comment by gulbanana** [comment]
ok
