### ISSUE TITLE
Self terminating the TestHost when the VS process goes away.

### ISSUE THREAD

**Issue by vijayrkn** [aspnet/Testing#92]
We need to kill all DNX instances when the VS process goes away. This is how it is currently done for DTH. We need to do something similar for TestHost as well.

                // Add a watch to the host PID. If it goes away we will self terminate.
                var hostProcess = Process.GetProcessById(hostPID);
                hostProcess.EnableRaisingEvents = true;
                hostProcess.Exited += (s, e) =>
                {
                    Process.GetCurrentProcess().Kill();
                };

**Comment by davidfowl** [comment]
Lets do this in beta5

**Comment by Eilon** [comment]
Need to implement in TestHost. Can try the suicide behavior by using the test UI.

VS also needs to tell TestHost which process to watch, which is tracked here: https://github.com/aspnet/Tooling/issues/187

**Comment by kichalla** [comment]
de44d22f99b1ad51cfff9ce74162080bed508b93
